<h3>Welcome <?=$this->username?>,</h3>

<p>Below you can directly access the information about your saved sites.</p>

<table>
    <thead>
        <tr>
            <td>URL</td>
            <td>Handshake</td>
            <td>Login</td>
            <td>Updates</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->sites as $site): ?>
            <tr>
                <td><a href="<?=$site['url']?>" target="_blank"><?=$site['url']?></a></td>
                <td><?=$site['isConnected'] ? 'Y' : 'N'?></td>
                <td><?=$site['isAuthenticated'] ? 'Y' : 'N'?></td>
                <td>
                    <?php if($site['numUpdates'] > 0):?>
                        <a href="/updates"><?=$site['numUpdates'] ?></a>
                    <?php else: ?>
                        <?=$site['numUpdates'] ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>