<!doctype html>
<html lang="en">
    <head>
        <title>WPTool - Manage Wordpress sites like a boss</title>
        <link rel="stylesheet" href="/resources/css/wptools.css" type="text/css" />
    </head>
    <body>
        <div id="header"> <div id="logged-in-as">
            <?php echo $this->loggedInAs(); ?> </div>
        </div>
        <h1>WPTool</h1>
        <h2>Manage Wordpress like a boss!</h2>
        <?php echo $this->layout()->content; ?>
        <p><a href="/resources/wptool.zip">Download Wordpress plugin</a></p>
        <footer>WPTool &copy; <?=date('Y')?>, Martin de Keijzer</footer>
    </body>
</html>