<p><a href="/sites/add">Add a new site</a></p>

<table>
    <thead>
        <tr>
            <td>Site URL</td>
            <td>Actions</td>
        </tr>
    </thead>
    <tbody>
        <?php if (!count($this->sites)): ?>
            <tr>
                <td colspan="2">There are no sites defined</td>
            </tr>
        <?php endif ?>
        <?php foreach($this->sites as $site): ?>
            <tr>
                <td><a href="sites/edit?siteid=<?=$site->id?>"><?=$site->url?></a></td>
                <td><a href="sites/delete?siteid=<?=$site->id?>">[X]</a></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>